name: Checkstyle action
on: [push]
jobs:
  checktyle-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v3.9.0
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'maven'
      - name: Build and Checkstyle with Maven
        run: mvn checkstyle:check compile
